CA: DAP-3150, DAP-3151, DAP-3161
dapplets/dapplet-extension pull request #127
Opened 2023-03-13 08:19 UTC by Ni-2

#### What is the purpose of this pull request? (put an "X" next to an item)

[x] New feature

#### What changes did you make? (Give an overview)

DAP-3150: WalletConnect(ETH) support in Connected Accounts

DAP-3151: show CA list for Rthereum wallets

DAP-3161: add dropodown for selecting wallet to show CA list

2023-03-15 09:16 UTC, alsakhaev requested changes

2023-03-15 09:28 UTC, Ni-2 commented on src/contentscript/overlay/root/components/CAUserButton/index.tsx
> +  colour?: string
https://www.google.com/search?q=color+or+colour&oq=color+or+colour&aqs=chrome..69i57j0i512l9.5462j0j7&sourceid=chrome&ie=UTF-8

2023-03-15 09:40 UTC, Ni-2 commented on src/contentscript/overlay/root/components/CAUserButton/index.tsx
> +  colour?: string
fixed

2023-03-15 09:40 UTC, Ni-2 commented on src/contentscript/overlay/root/components/CAUserButton/index.tsx
> +  handleOpenPopup?: (account: IConnectedAccountUser) => Promise<void>
fixed

2023-03-15 13:41 UTC, merged

2023-03-15 13:45 UTC, alsakhaev commented
:tada: This PR is included in version 0.53.0-alpha.32 :tada:

The release is available on:
- [npm package (@develop dist-tag)](https://www.npmjs.com/package/@dapplets/dapplet-extension/v/0.53.0-alpha.32)
- `v0.53.0-alpha.32`
- [GitHub release](https://github.com/dapplets/dapplet-extension/releases/tag/v0.53.0-alpha.32)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-03-18 12:52 UTC, alsakhaev commented
:tada: This PR is included in version 0.55.0-alpha.1 :tada:

The release is available on:
- [npm package (@develop dist-tag)](https://www.npmjs.com/package/@dapplets/dapplet-extension/v/0.55.0-alpha.1)
- `v0.55.0-alpha.1`
- [GitHub release](https://github.com/dapplets/dapplet-extension/releases/tag/v0.55.0-alpha.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-18 11:36 UTC, alsakhaev commented
:tada: This PR is included in version 0.55.0-beta.1 :tada:

The release is available on:
- [npm package (@testing dist-tag)](https://www.npmjs.com/package/@dapplets/dapplet-extension/v/0.55.0-beta.1)
- `v0.55.0-beta.1`
- [GitHub release](https://github.com/dapplets/dapplet-extension/releases/tag/v0.55.0-beta.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-05-18 12:14 UTC, alsakhaev commented
:tada: This PR is included in version 0.55.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dapplets/dapplet-extension/v/0.55.0)
- `v0.55.0`
- [GitHub release](https://github.com/dapplets/dapplet-extension/releases/tag/v0.55.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: