Dap 3753
dapplets/dapplet-extension pull request #188
Opened 2023-07-28 11:54 UTC by Lisofffa

#### What is the purpose of this pull request? (put an "X" next to an item)

[ ] Bug fix
[ ] New feature
[ ] Documentation update
[ ] Add something to the core
[ ] Other, please explain:

#### Add a reference to a related issue if it exists

*issue:* 

#### What changes did you make? (Give an overview)

#### Is there anything you'd like reviewers to focus on?

2023-07-28 13:36 UTC, alsakhaev requested changes

2023-07-28 13:36 UTC, alsakhaev commented on src/contentscript/overlay/root/components/OverlayToolbar/Notification/index.tsx
> +  }
Move to useEffect and don't forget to unsubscribe (clearTimeout)

2023-07-28 14:22 UTC, merged

2023-07-28 14:29 UTC, alsakhaev commented
:tada: This PR is included in version 0.56.0-alpha.58 :tada:

The release is available on:
- [npm package (@develop dist-tag)](https://www.npmjs.com/package/@dapplets/dapplet-extension/v/0.56.0-alpha.58)
- `v0.56.0-alpha.58`
- [GitHub release](https://github.com/dapplets/dapplet-extension/releases/tag/v0.56.0-alpha.58)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-28 17:01 UTC, alsakhaev commented
:tada: This PR is included in version 0.56.0-beta.4 :tada:

The release is available on:
- [npm package (@testing dist-tag)](https://www.npmjs.com/package/@dapplets/dapplet-extension/v/0.56.0-beta.4)
- `v0.56.0-beta.4`
- [GitHub release](https://github.com/dapplets/dapplet-extension/releases/tag/v0.56.0-beta.4)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-07-28 18:14 UTC, alsakhaev commented
:tada: This PR is included in version 0.56.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@dapplets/dapplet-extension/v/0.56.0)
- `v0.56.0`
- [GitHub release](https://github.com/dapplets/dapplet-extension/releases/tag/v0.56.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

2023-08-29 10:24 UTC, Gromazek commented
test

2023-08-29 10:54 UTC, Gromazek commented
test